version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiogram_bot_with_openai
    environment:
      TELEGRAM_API_TOKEN: "your-telegram-api-token"
      OPENAI_API_KEY: "your-openai-api-key"
    volumes:
      - .:/app
    restart: unless-stopped
